apiVersion: v1
kind: Pod
metadata:
  name: shell-demo-vol
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: customer-vol
      mountPath: /etc/customer1
  volumes:
    - name: customer-vol
      configMap:
        name: customer1